import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Link,useLocation}from'react-router-dom';
import{Menu,X,ArrowRight,ArrowUpRight,Search,ChevronDown,Users,Building2,House,Palmtree,Handshake,Check,Phone,Mail}from'lucide-react';
import'./style.css';

const nav=[['Home','/'],['About','/about'],['Properties','/owners'],['Property Management','/management'],['Vacation Homes','/vacation-homes'],['Buy / Sell / Lease','/brokerage'],['Contact','/contact']];
const HERO='https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=90';
const CAMP='https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=90';
const VILLA='https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=90';
const APARTMENT='https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=90';
const HOME_HERO='/images/hero-residences.webp';
const CARD_LABOUR='/images/card-labour-staff.webp';
const CARD_BUILDINGS='/images/card-full-buildings.webp';
const CARD_VILLAS='/images/card-villas.webp';
const CARD_APARTMENTS='/images/card-apartments.webp';
const UAE_MAP='/images/uae-map.webp';

function Logo(){return <Link className="brand" to="/" aria-label="Rokn Al Ahlam home"><img className="brand-logo" src="/ra-logo-approved.png" alt="Rokn Al Ahlam Real Estate"/></Link>}
function Header(){const[open,setOpen]=useState(false);const p=useLocation().pathname;return <header className={p==='/'?'home-header':''}><Logo/><button className="mobile-toggle" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(([label,url])=><Link key={url} className={p===url?'active':''} to={url} onClick={()=>setOpen(false)}>{label}</Link>)}<span className="search-wrap"><Search size={19}/><i/></span><span className="lang">EN <ChevronDown size={14}/></span><Link className="nav-cta" to="/contact#list">List Your Property <ArrowRight size={16}/></Link></nav></header>}
function Seo({title,description}){React.useEffect(()=>{document.title=title;const m=document.querySelector('meta[name="description"]');if(m)m.content=description;const c=document.querySelector('link[rel="canonical"]');if(c)c.href='https://roknalahlam.com'+location.pathname},[title,description]);return null}
const Btn=({to='/contact#list',children,outline=false})=><Link className={'button '+(outline?'outline':'')} to={to}>{children}<ArrowRight size={16}/></Link>;

const serviceStrip=[
  [Users,'Labour & Staff','Accommodation'],[Building2,'Full Buildings','Management'],[House,'Villas & Apartments',''],[Palmtree,'Vacation Homes',''],[Handshake,'Leasing, Sales &','Brokerage']
];
const cards=[
  ['Labour & Staff','Accommodation','Safe, well-managed accommodation for a productive workforce.',CARD_LABOUR,'/management'],
  ['Full Buildings','Management','Complete management for residential and commercial buildings.',CARD_BUILDINGS,'/management'],
  ['Villas','','Quality living in prime locations across Dubai, Sharjah and Ajman.',CARD_VILLAS,'/owners'],
  ['Apartments','','Find or list apartments for rent or sale with expert support.',CARD_APARTMENTS,'/brokerage']
];

function Home(){return <><Seo title="Rokn Al Ahlam | Real Estate. Professionally Managed." description="Property management, leasing, vacation homes and brokerage across Dubai, Sharjah and Ajman."/><div className="reference-home"><section className="reference-hero"><img className="hero-bg" src={HOME_HERO} alt="Managed residences and modern tower at golden hour"/><div className="hero-left"><p className="eyebrow">YOUR PROPERTY. OUR COMMITMENT.</p><h1>Real Estate.<br/>Professionally Managed.</h1><p className="hero-copy">End-to-end property management, leasing, vacation home management and real estate brokerage across Dubai, Sharjah and Ajman.</p><div className="hero-actions"><Btn>List Your Property</Btn><Btn outline to="/management">Our Services</Btn></div></div><aside className="hero-side"><div className="emirates">Dubai<br/>Sharjah<br/>Ajman</div><span className="gold-line"/><div className="side-words">PEOPLE<br/>PROPERTIES<br/>POSSIBILITIES</div></aside></section><section className="service-strip">{serviceStrip.map(([Icon,a,b])=><Link key={a} to="/management"><Icon/><span>{a}{b&&<><br/>{b}</>}</span></Link>)}<div className="experience"><b>15+</b><span>Years of Real Estate Experience</span></div></section><section className="solutions"><div className="section-head"><div><p className="eyebrow">PROPERTY SOLUTIONS</p><h2>For Owners, Investors and Tenants</h2></div><Link to="/owners">View All Properties <ArrowRight size={17}/></Link></div><div className="property-card-grid">{cards.map(([a,b,txt,img,to])=><Link className="property-card" key={a} to={to}><img src={img} alt={a+(b?' '+b:'')}/><div className="shade"/><div className="card-copy"><h3>{a}{b&&<><br/>{b}</>}</h3><p>{txt}</p><span>Explore <ArrowRight size={15}/></span></div></Link>)}</div></section><section className="operating"><div><p className="eyebrow">OPERATING ACROSS</p><h2>Dubai, Sharjah and Ajman</h2></div><div className="operating-copy"><p>We work with property owners, tenants and investors across all three emirates, providing practical, reliable and sustainable real estate solutions.</p><Btn to="/contact">Contact Our Team</Btn></div><div className="uae-map"><img src={UAE_MAP} alt="Map of Dubai, Sharjah and Ajman"/></div></section></div></>}

function PageHero({label,title,text,image=HERO}){return <section className="page-hero"><img src={image} alt=""/><div><p className="eyebrow">{label}</p><h1>{title}</h1><p>{text}</p></div></section>}
const management=['Occupancy coordination','Rental & payment administration','Cleaning & maintenance','Utility & service management','Routine inspections','Vacancy management','Move-in & move-out coordination','Contract coordination','Clear owner reporting'];
function About(){return <><Seo title="About Rokn Al Ahlam | UAE Real Estate" description="Rokn Al Ahlam serves property owners and seekers across Dubai, Sharjah and Ajman."/><PageHero label="About us" title="Property is personal. Operations should be professional." text="15+ years of real estate experience across property operations, vacation homes and brokerage."/><section className="content-grid"><div><h2>A steady hand in a fast-moving market.</h2></div><div><p>We work at the intersection of property operations, vacation homes and brokerage with practical communication and accountable coordination.</p></div></section></>}
function OwnerPage(){return <><Seo title="For Property Owners | Rokn Al Ahlam" description="Property operations and annual lease opportunities across Dubai, Sharjah and Ajman."/><PageHero label="For property owners" title="You Own the Property. We Handle the Operation." text="Operational clarity, careful coordination and practical reporting." image={CAMP}/><section className="content-grid"><div><h2>Ownership without the daily operational burden.</h2><p>For suitable properties, we also discuss annual lease opportunities on flexible commercial terms.</p><Btn>Discuss Your Property</Btn></div><div className="checklist">{management.map(x=><p key={x}><Check/> {x}</p>)}</div></section></>}
function Management(){return <><Seo title="Property Management Dubai, Sharjah & Ajman | Rokn Al Ahlam" description="Professional property management for buildings, villas, apartments and staff accommodation."/><PageHero label="Property management" title="Operational discipline, property by property." text="Management and supervision tailored to buildings, villas, apartments and staff accommodation." image={CAMP}/><section className="content-grid"><div><h2>A complete operational view.</h2><p>We coordinate occupancy, administration, cleaning, maintenance, utilities, inspections, handovers and vacancy response.</p></div><div className="checklist">{management.map(x=><p key={x}><Check/> {x}</p>)}</div></section></>}
function Vacation(){return <><Seo title="Vacation Home Management Dubai | Rokn Al Ahlam" description="Vacation home rental and management services for property owners."/><PageHero label="Vacation homes" title="Your property. Our complete management." text="Two commercial models for suitable properties: Revenue Management and Fixed Rental Arrangement." image={APARTMENT}/><section className="content-grid"><div><h2>Revenue Management</h2><p>We manage the day-to-day rental operation, cleaning, maintenance, utilities, administration and guest coordination.</p></div><div><h2>Fixed Rental Arrangement</h2><p>For suitable properties, an annual rental arrangement can be explored subject to licensing, permits and eligibility.</p></div></section></>}
function Brokerage(){return <><Seo title="Real Estate Brokerage Dubai, Sharjah & Ajman | Rokn Al Ahlam" description="Buy, sell and lease residential and commercial property across Dubai, Sharjah and Ajman."/><PageHero label="Buy · sell · lease" title="Clearer property moves, from search to signature." text="For owners and seekers across residential, commercial, ready, investment and off-plan property." image={HERO}/><section className="content-grid"><div><h2>I Own a Property</h2><p>Position your property for the right leasing, sale or investment conversation.</p><Btn>List My Property</Btn></div><div><h2>I’m Looking for a Property</h2><p>Tell us what matters and we will guide you through suitable opportunities.</p><Btn to="/contact#looking">Start My Search</Btn></div></section></>}
function Form({title,fields,id}){return <form id={id} onSubmit={e=>{e.preventDefault();alert('Thank you. Your enquiry is ready for our team.')}}><h3>{title}</h3>{fields.map((f,i)=><label key={f}>{f}{i<3&&<b>*</b>}<input required={i<3} type={f.includes('Email')?'email':f.includes('Phone')?'tel':'text'} placeholder={f}/></label>)}<button className="button" type="submit">Send Enquiry <ArrowRight size={16}/></button></form>}
function Contact(){return <><Seo title="Contact Rokn Al Ahlam" description="Contact Rokn Al Ahlam about property management, vacation homes, leasing, sales and brokerage."/><section className="contact-title"><p className="eyebrow">CONTACT</p><h1>Let’s start with the right conversation.</h1></section><section className="forms" id="list"><Form title="List My Property" fields={['Full name','Phone number','Email address','Property type','Property location','Message']}/><Form title="Looking for Property" id="looking" fields={['Full name','Phone number','Email address','Property type needed','Preferred location','Budget or requirements']}/><Form title="Staff Accommodation Requirement" fields={['Company / contact name','Phone number','Email address','Preferred area','Number of occupants','Requirements']}/><Form title="Vacation Home Owner" fields={['Full name','Phone number','Email address','Property location','Preferred model','Property details']}/></section></>}
function Footer(){return <footer><Logo/><p>Real estate management, vacation homes and brokerage across Dubai, Sharjah and Ajman.</p><div><a href="mailto:hello@roknalahlam.com"><Mail size={15}/> hello@roknalahlam.com</a><a href="tel:+971000000000"><Phone size={15}/> +971 00 000 0000</a></div></footer>}
function ScrollToHash(){const l=useLocation();React.useEffect(()=>{if(l.hash){const e=document.getElementById(l.hash.slice(1));if(e)e.scrollIntoView()}},[l]);return null}
function App(){return <BrowserRouter><ScrollToHash/><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/owners" element={<OwnerPage/>}/><Route path="/management" element={<Management/>}/><Route path="/vacation-homes" element={<Vacation/>}/><Route path="/brokerage" element={<Brokerage/>}/><Route path="/contact" element={<Contact/>}/></Routes></main><Footer/></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
