import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Link,useLocation}from'react-router-dom';
import{Menu,X,ArrowRight,ArrowUpRight,Search,ChevronDown,Users,Building2,House,Palmtree,Handshake,Check,Phone,Mail,MapPin}from'lucide-react';
import'./style.css';

const nav=[['Home','/'],['About','/about'],['Properties','/owners'],['Property Management','/management'],['Vacation Homes','/vacation-homes'],['Contact','/contact']];
const HOME_HERO='/images/hero-residences.webp';
const CARD_LABOUR='/images/card-labour-staff.webp';
const CARD_BUILDINGS='/images/card-full-buildings.webp';
const CARD_VILLAS='/images/card-villas.webp';
const CARD_APARTMENTS='/images/card-apartments.webp';
const UAE_MAP='/images/uae-map.webp';

function Logo(){return <Link className="brand" to="/" aria-label="Rokn Al Ahlam home"><img className="brand-logo" src="/ra-logo-approved.png" alt="Rokn Al Ahlam Real Estate"/></Link>}
function Header(){const[open,setOpen]=useState(false);const p=useLocation().pathname;React.useEffect(()=>{const h=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);return <header className={p==='/'?'home-header':''}><Logo/><button className="mobile-toggle" aria-expanded={open} onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}><span className="nav-links">{nav.map(([label,url])=><Link key={url} className={p===url?'active':''} to={url} onClick={()=>setOpen(false)}>{label}</Link>)}</span><span className="search-wrap"><Search size={19}/><i/></span><span className="lang">EN <ChevronDown size={14}/></span><Link className="nav-cta" to="/contact#list">List Your Property <ArrowRight size={16}/></Link></nav></header>}
function Seo({title,description}){React.useEffect(()=>{document.title=title;const m=document.querySelector('meta[name="description"]');if(m)m.content=description;const c=document.querySelector('link[rel="canonical"]');if(c)c.href='https://roknalahlam.com'+location.pathname;const ot=document.querySelector('meta[property="og:title"]');if(ot)ot.content=title;const od=document.querySelector('meta[property="og:description"]');if(od)od.content=description},[title,description]);return null}
const Btn=({to='/contact#list',children,outline=false,noArrow=false})=><Link className={'button '+(outline?'outline':'')} to={to}>{children}{!noArrow&&<ArrowRight size={16}/>}</Link>;

const serviceStrip=[
  [Users,'Labour & Staff','Accommodation','/management#staff-accommodation'],[Building2,'Full Buildings','Management','/management#buildings'],[House,'Villas & Apartments','','/management#villas'],[Palmtree,'Vacation Homes','','/vacation-homes'],[Handshake,'Leasing','Coordination','/brokerage']
];
const cards=[
  ['Labour & Staff','Accommodation','Professionally managed accommodation solutions for companies requiring reliable, coordinated staff housing.',CARD_LABOUR,'/management#staff-accommodation'],
  ['Full Buildings','','End-to-end management and leasing coordination for residential and commercial buildings.',CARD_BUILDINGS,'/management#buildings'],
  ['Villas','','Owner representation, property management and leasing coordination for villas across Dubai, Sharjah and Ajman.',CARD_VILLAS,'/management#villas'],
  ['Apartments','','Property management, leasing coordination and holiday-home management for individual apartments and portfolios.',CARD_APARTMENTS,'/management#apartments']
];
const beliefs=[['Clarity','Straightforward communication and transparent reporting at every step.'],['Responsibility','We treat every property as if it were our own to protect.'],['Practicality','Solutions built around what actually works for the property and the owner.'],['Long-Term Relationships','We aim to be the team owners keep coming back to.']];
const services=[['Property Management','Day-to-day operations, maintenance coordination and owner reporting.'],['Leasing','Tenant sourcing, vetting and lease coordination.'],['Staff Accommodation','Coordinated housing solutions for company workforces.'],['Vacation Homes','Revenue management and guest operations for short-term rentals.']];
const vacationScope=['Property readiness','Guest administration','Cleaning coordination','Maintenance coordination','Utilities and payment coordination'];
const eligibility=['Property suitability and eligibility','Applicable licensing and permit requirements','Commercial agreement'];
const steps=[['Understand the property','We review the property type, location and current status.'],['Understand the owner’s objective','We clarify what the owner wants from the property, so the scope matches the objective.'],['Build the right operating plan','Scope and commercial terms are structured around the property type, operating requirements and owner objectives.'],['Maintain clear communication','Practical communication, clear follow-up and owner reporting throughout.']];

function Home(){return <><Seo title="Rokn Al Ahlam | Real Estate. Professionally Managed." description="Professional property management, leasing and owner support for buildings, villas, apartments and staff accommodation across Dubai, Sharjah and Ajman."/><div className="reference-home"><section className="reference-hero"><img className="hero-bg" fetchPriority="high" src={HOME_HERO} alt="Managed residences and modern tower at golden hour"/><div className="hero-left"><p className="eyebrow">YOUR PROPERTY. OUR COMMITMENT.</p><h1>Real Estate.<br/>Professionally Managed.</h1><p className="hero-copy">Professional property management, leasing and owner support for buildings, villas, apartments and staff accommodation across Dubai, Sharjah and Ajman.</p><div className="hero-actions"><Btn>List Your Property</Btn><Btn outline noArrow to="/contact#list">Enquire Now</Btn></div></div><aside className="hero-side"><div className="emirates">Dubai<br/>Sharjah<br/>Ajman</div><span className="gold-line"/><div className="side-words">PEOPLE<br/>PROPERTIES<br/>POSSIBILITIES</div></aside></section><section className="service-strip">{serviceStrip.map(([Icon,a,b,to])=><Link key={a} to={to}><Icon/><span>{a}{b&&<><br/>{b}</>}</span></Link>)}<div className="experience"><b>15+</b><span>Years of Real Estate Experience</span></div></section><section className="solutions"><div className="section-head"><div><p className="eyebrow">FOR PROPERTY OWNERS AND LANDLORDS</p><h2>You Own the Property. We Handle the Operation.</h2></div><Link to="/owners">View All Properties <ArrowRight size={17}/></Link></div><section className="content-grid"><div><h2>Professional management for buildings, villas, apartments and staff accommodation across Dubai, Sharjah and Ajman.</h2></div><div><p>From occupancy and rent administration to maintenance, inspections, tenant coordination and owner reporting, Rokn Al Ahlam manages the day-to-day work that protects your property and keeps it commercially active.</p></div></section><div className="editorial-list cols-2">{ownerBenefits.map(x=><p key={x}><Check/> {x}</p>)}</div></section><section className="operating"><div><p className="eyebrow">OPERATING ACROSS</p><h2>Dubai, Sharjah and Ajman</h2></div><div className="operating-copy"><p>We work with property owners, tenants and investors across all three emirates, providing practical, reliable and sustainable real estate solutions.</p></div><div className="uae-map"><img loading="lazy" src={UAE_MAP} alt="Map of Dubai, Sharjah and Ajman"/></div></section><FinalCta eyebrow="READY WHEN YOU ARE" title="Tell Us About Your Property" text="Share the property details and our team will recommend the most suitable management, leasing or vacation-home route."/></div></>}

function PageHero({label,title,text,image=HOME_HERO}){return <section className="page-hero"><img src={image} alt=""/><div><p className="eyebrow">{label}</p><h1>{title}</h1><p>{text}</p></div></section>}
function FinalCta({eyebrow,title,text,to,label='Enquire Now',note}){return <section className="final-cta"><div className="cta-panel"><div className="cta-copy"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{text}</p>{note&&<p className="cta-note">{note}</p>}</div><div className="cta-actions"><Btn to={to}>{label}</Btn><a className="cta-phone" href="tel:+971556829779"><Phone size={16}/> Call +971 55 682 9779</a></div></div></section>}
const whyOwners=['One team for property operations, leasing and owner coordination','Practical communication and clear follow-up','Flexible commercial arrangements depending on property type and owner objectives','Experience across buildings, villas, apartments and staff accommodation'];
const management=['Occupancy coordination','Rental and payment administration','Maintenance','Cleaning','Utility coordination','Inspections','Vacancy management','Move-in and move-out coordination','Contract coordination','Owner reporting'];
const ownerBenefits=['Occupancy and tenant coordination','Rent and payment administration','Maintenance and inspections','Vacancy management','Move-in and move-out coordination','Utilities and service coordination','Contract coordination','Clear owner reporting'];
function About(){return <><Seo title="About Rokn Al Ahlam | UAE Real Estate" description="Rokn Al Ahlam: 15+ years in property management, building, villa and apartment management for landlords across Dubai, Sharjah and Ajman."/><PageHero label="About us" title="Real Estate Is Personal. Operations Should Be Professional." text="15+ years of real estate experience across property operations and vacation homes."/><section className="about-section"><h2>A Practical Real Estate Partner</h2><div className="about-body"><p>A steady hand in a fast-moving market: Rokn Al Ahlam works with property owners, investors, tenants and businesses across Dubai, Sharjah and Ajman. Our work brings together property management, leasing and vacation home operations under one coordinated team.</p><p>With more than 15 years of real estate experience, our approach is practical: understand the property, understand the owner’s objective, build the right operating plan and maintain clear communication throughout.</p><div className="facts"><div className="fact"><b>15+</b><span>Years of real estate experience</span></div><div className="fact"><b>3</b><span>Emirates served: Dubai, Sharjah and Ajman</span></div><div className="fact"><b>4</b><span>Property types: buildings, villas, apartments and staff accommodation</span></div></div></div></section><section className="about-section tint"><h2>What We Believe</h2><div className="about-body"><p>Good property management is not just collecting rent. It is protecting the asset, coordinating people, resolving issues quickly and keeping the owner informed.</p><div className="principles">{beliefs.map(([t,d],i)=><div className="principle" key={t}><span className="num" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section><section className="about-section"><h2>What We Do</h2><div className="about-body"><p>Four areas of work, delivered by one coordinated team.</p><div className="service-rows">{services.map(([t,d],i)=><div className="service-row" key={t}><span className="row-num" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section><section className="about-section tint areas-served"><h2>Areas Served</h2><div className="about-body"><p className="areas-big">Dubai<i aria-hidden="true"/>Sharjah<i aria-hidden="true"/>Ajman</p><p>We operate across Dubai, Sharjah and Ajman, working with property owners, tenants, investors and businesses throughout all three emirates.</p></div></section><FinalCta eyebrow="WORK WITH US" title="Tell Us About Your Property" text="Share the property details and our team will recommend the most suitable management, leasing or vacation-home route."/></>}
function OwnerPage(){return <><Seo title="For Property Owners | Rokn Al Ahlam" description="For landlords and property owners: building, villa and apartment management, leasing and annual lease options across Dubai, Sharjah and Ajman."/><PageHero label="For property owners" title="Property Opportunities Across Dubai, Sharjah and Ajman." text="Whether you own property, need accommodation, are looking to rent or want to buy, our team can help identify the right route." image={CARD_BUILDINGS}/><section className="solutions"><div className="property-card-grid">{cards.map(([a,b,txt,img,to])=><Link className="property-card" key={a} to={to}><img loading="lazy" src={img} alt={a+(b?' '+b:'')}/><div className="shade"/><ArrowUpRight className="card-arrow" aria-hidden="true"/><div className="card-copy"><h3>{a}{b&&<><br/>{b}</>}</h3><p>{txt}</p></div></Link>)}</div></section><section className="content-grid lead owner-ops"><div><h2>Ownership without the daily operational burden.</h2><p>For suitable properties, we also discuss annual lease opportunities on flexible commercial terms.</p><Btn>Enquire Now</Btn></div><div className="editorial-list cols-2">{management.map(x=><p key={x}><Check/> {x}</p>)}</div></section><section className="content-grid lead owner-broker band-ivory"><div><h2>Property Owners Need Consistent, Hands-On Management.</h2><p>From occupancy and maintenance to leasing, reporting and day-to-day coordination, Rokn Al Ahlam helps owners operate property with less friction and clearer accountability.</p><Btn>Enquire Now</Btn><p>Share the property details and our team will recommend the most suitable management, leasing or vacation-home route.</p></div><div><div className="editorial-list"><h3>Why Owners Work With Us</h3>{whyOwners.map(x=><p key={x}><Check/> {x}</p>)}</div><div className="owner-cta-row"><Btn>I Own a Property</Btn><Btn to="/contact#looking">I’m Looking for a Property</Btn></div></div></section></>}
function Management(){return <><Seo title="Property Management Dubai, Sharjah & Ajman | Rokn Al Ahlam" description="Owner-focused property management: occupancy, rent administration, maintenance, inspections and clear owner reporting across Dubai, Sharjah and Ajman."/><PageHero label="Property management" title="You Own the Property. We Handle the Operation." text="Property ownership creates value, but it also creates daily operational work. Rokn Al Ahlam coordinates the activity required to keep properties occupied, maintained, supported and commercially responsive." image={CARD_VILLAS}/><section className="content-grid lead wide"><div><h2>Who We Serve</h2><p>Rokn Al Ahlam manages property for owners, investors and companies across Dubai, Sharjah and Ajman, taking on the day-to-day work so the owner does not have to.</p></div><div className="type-grid">{cards.map(([a,b,txt,,to])=><div className="type" id={to.split('#')[1]} key={a}><h3>{a}{b&&' '+b}</h3><p>{txt}</p></div>)}</div></section><section className="content-grid lead band-ivory"><div><h2>Services</h2><p>The scope below covers the day-to-day work of operating a managed property.</p><h3 className="sub">Flexible Commercial Arrangements</h3><p>Management scope and commercial terms are structured around the property type, operating requirements and owner objectives.</p></div><div className="editorial-list cols-2">{management.map(x=><p key={x}><Check/> {x}</p>)}</div></section><section className="block"><div className="block-head"><h2>How Management Works</h2><p>Our approach is practical: understand the property, understand the owner’s objective, build the right operating plan and maintain clear communication throughout.</p></div><div className="steps">{steps.map(([t,d],i)=><div className="step" key={t}><span className="num" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section><section className="content-grid lead band-ivory"><div><h2>Why Choose Rokn Al Ahlam</h2><p>What owners can expect when they work with our team.</p></div><div className="editorial-list">{whyOwners.map(x=><p key={x}><Check/> {x}</p>)}</div></section><FinalCta eyebrow="FOR PROPERTY OWNERS" title="Request a Property Assessment" text="Share the property details and our team will recommend the most suitable management route."/></>}
function Vacation(){return <><Seo title="Vacation Home Management Dubai | Rokn Al Ahlam" description="Vacation home rental and management services for property owners."/><PageHero label="Vacation homes" title="Your Property. Professionally Operated." text="For eligible properties, Rokn Al Ahlam can coordinate the day-to-day work required to operate a vacation home. This runs from property readiness and guest administration through to cleaning, maintenance, utilities and payment coordination." image={CARD_APARTMENTS}/><section className="block models"><div className="block-head"><p className="eyebrow">TWO AVAILABLE MODELS</p><h2>Operating Models</h2><p>For eligible vacation-home properties, Rokn Al Ahlam may consider two operating arrangements depending on the property and commercial suitability.</p></div><div className="model-grid"><article className="model"><span className="opt">Option 01</span><h3>Revenue Management / Revenue Sharing</h3><p>For suitable properties, Rokn Al Ahlam may coordinate vacation-home operations under a revenue-based arrangement aligned with operating performance and agreed terms.</p></article><article className="model"><span className="opt">Option 02</span><h3>Fixed Rental Arrangement</h3><p>For selected properties, a fixed rental arrangement may also be considered, subject to property suitability and commercial agreement.</p></article></div></section><section className="content-grid lead band-ivory"><div><h2>What’s Included</h2><p>For eligible properties, Rokn Al Ahlam can coordinate the practical, day-to-day work behind a vacation home. Coverage depends on the property and the arrangement selected.</p></div><div className="editorial-list cols-2">{vacationScope.map(x=><p key={x}><Check/> {x}</p>)}</div></section><section className="content-grid lead"><div><h2>Eligibility</h2><p>Not every property qualifies for vacation-home operation. Whether an arrangement can be considered depends on the following.</p></div><div className="editorial-list">{eligibility.map(x=><p key={x}><Check/> {x}</p>)}</div></section><FinalCta eyebrow="FOR ELIGIBLE PROPERTIES" title="Discuss Your Vacation Home" text="Tell us about the property and our team will discuss which arrangement may be suitable, subject to eligibility." note="Vacation-home operations are subject to applicable licensing, permit and property eligibility requirements." to="/contact#vacation"/></>}
function Brokerage(){return <><Seo title="Property Leasing | Rokn Al Ahlam" description="Property leasing support for owners and tenants across residential and commercial property in Dubai, Sharjah and Ajman."/><PageHero label="Property leasing" title="Practical Leasing Support, From Listing to Signature." text="For owners looking to lease their property and tenants searching for the right fit across Dubai, Sharjah and Ajman." image={CARD_LABOUR}/><section className="content-grid"><div><h2>I Own a Property to Lease</h2><p>Share the property details and our team will assess the right leasing route and target tenant profile.</p><Btn>Enquire Now</Btn></div><div><h2>I’m Looking for a Property</h2><p>Tell us your location, property type, budget and timing. We will help identify suitable rental opportunities.</p><Btn to="/contact#looking">Start My Property Search</Btn></div></section><section className="text-block band-ivory"><h2>Property Types</h2><p>Residential and commercial leasing across villas, apartments, full buildings and staff accommodation.</p></section></>}
const EMAIL_RE=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function leadError(f,v){const s=(v||'').toString().trim();if(f.t==='consent')return v?'':'Please confirm your consent so we can contact you.';if(f.r&&!s)return f.l+' is required.';if(s&&f.t==='email'&&!EMAIL_RE.test(s))return 'Enter a valid email address.';if(s&&f.t==='tel'&&s.replace(/\D/g,'').length<7)return 'Enter a valid phone number.';return '';}
function readUtm(){try{const q=new URLSearchParams(location.search);const o={};['utm_source','utm_medium','utm_campaign','utm_term','utm_content'].forEach(k=>{const v=q.get(k);if(v)o[k]=v});return o;}catch(e){return {};}}
async function submitLead(payload){await new Promise(r=>setTimeout(r,600));try{const k='ra_lead_outbox';const box=JSON.parse(localStorage.getItem(k)||'[]');box.push(payload);localStorage.setItem(k,JSON.stringify(box));}catch(e){}if(window.console&&console.info)console.info('[lead-qa] structured payload:',payload);return {ok:true,reference:'RA-'+Date.now().toString(36).toUpperCase().slice(-6)};}
function LeadField({f,val,set,err,id}){const fid=(id||'f')+'-'+f.n,eid=fid+'-err';if(f.t==='consent')return <div className="field" key={f.n}><label className="consent-row" htmlFor={fid}><input id={fid} type="checkbox" checked={!!val} onChange={e=>set(f.n,e.target.checked)} aria-invalid={err?'true':undefined} aria-describedby={err?eid:undefined}/><span>{f.l}{f.r&&<b>*</b>}</span></label>{err&&<p className="field-err" id={eid} role="alert">{err}</p>}</div>;const shared={id:fid,value:val||'',onChange:e=>set(f.n,e.target.value),'aria-invalid':err?'true':undefined,'aria-describedby':err?eid:undefined};let input=null;if(f.t==='select')input=<select {...shared}><option value="">Select…</option>{f.o.map(function(o){return Array.isArray(o)?<option key={o[0]} value={o[0]}>{o[1]}</option>:<option key={o} value={o}>{o}</option>;})}</select>;else if(f.t==='textarea')input=<textarea {...shared} rows={3}/>;else input=<input {...shared} type={f.t} inputMode={f.t==='tel'?'tel':undefined}/>;return <div className="field" key={f.n}><label htmlFor={fid}>{f.l}{f.r&&<b>*</b>}</label>{input}{err&&<p className="field-err" id={eid} role="alert">{err}</p>}</div>;}
function LeadForm({id}){
const loc=useLocation();
const initialType=HASH_TYPE[loc.hash]||'owner-management';
const[etype,setEtype]=React.useState(initialType);
const[vails,setVails]=React.useState({etype:initialType});
const[errs,setErrs]=React.useState({});
const[st,setSt]=React.useState('idle');
const[rf,setRf]=React.useState('');
React.useEffect(()=>{const m=HASH_TYPE[loc.hash];if(m){setEtype(m);setVails(function(p){const c={};for(const k in p)c[k]=p[k];c.etype=m;return c;});setErrs({});}},[loc.hash]);
const fields=[{n:'etype',l:'What can we help you with?',t:'select',r:1,o:ENQUIRY_TYPES.map(function(t){return [t.v,t.l];})}].concat(COMMON_HEAD,EXTRAS[etype]||[],[NOTES_F,CONSENT_F]);
const set=function(n,v){const c={};for(const k in vails)c[k]=vails[k];c[n]=v;setVails(c);if(n==='etype'){setEtype(v);setErrs({});}};
const go=function(e){e.preventDefault();const ne={};for(let i=0;i<fields.length;i++){const m=leadError(fields[i],vails[fields[i].n]);if(m)ne[fields[i].n]=m;}setErrs(ne);if(Object.keys(ne).length)return;setSt('sending');const fd={};for(let i=0;i<fields.length;i++){const fl=fields[i];if(fl.t==='consent')continue;const vv=vails[fl.n];fd[fl.n]=(vv||'').toString().trim();}const payload={enquiryType:etype,timestamp:new Date().toISOString(),page:location.pathname,source:document.referrer||'',utm:readUtm(),consent:!!vails.consent,fields:fd};submitLead(payload).then(function(r){setRf(r.reference);setSt('sent');}).catch(function(){setSt('error');});};
const label=etypeLabel(etype);
if(st==='sent')return <form id={id} className="single"><h3>Tell Us What You Need</h3><p className="form-intro">Choose the type of enquiry and provide a few details. Our team will review your requirement and contact you regarding the next step.</p><p className="lead-ok"><Check/> Thank you — your enquiry has been received.</p><p>Enquiry <b>{label}</b> · Reference <b>{rf}</b>. Our team will contact you shortly. (Preview mode: saved locally for QA, nothing was sent.)</p><button className="button" type="button" onClick={function(){setSt('idle');setVails({etype:etype});setErrs({});setRf('');}}>Send another enquiry</button></form>;
return <form id={id} className="single" noValidate onSubmit={go}><h3>Tell Us What You Need</h3><p className="form-intro">Choose the type of enquiry and provide a few details. Our team will review your requirement and contact you regarding the next step.</p>{fields.map(function(f){return <LeadField key={f.n} f={f} id={id} val={vails[f.n]} set={set} err={errs[f.n]}/>;})} {st==='error'&&<p className="field-err" role="alert">Something went wrong. Please try again.</p>}<button className="button" type="submit" disabled={st==='sending'}>{st==='sending'?'Sending…':'Send Enquiry'} <ArrowRight size={16}/></button></form>;
}
const ENQUIRY_TYPES=[{v:'owner-management',l:'Property Owner / Property Management'},{v:'property-search',l:'Looking for a Property'},{v:'staff-accommodation',l:'Staff Accommodation Requirement'},{v:'vacation-home',l:'Vacation Home Owner'}];
const HASH_TYPE={'#list':'owner-management','#looking':'property-search','#staff':'staff-accommodation','#vacation':'vacation-home'};
function etypeLabel(v){for(let i=0;i<ENQUIRY_TYPES.length;i++)if(ENQUIRY_TYPES[i].v===v)return ENQUIRY_TYPES[i].l;return v;}
const COMMON_HEAD=[{n:'name',l:'Name / Contact Person',t:'text',r:1},{n:'phone',l:'Phone',t:'tel',r:1},{n:'whatsapp',l:'WhatsApp',t:'tel'},{n:'email',l:'Email',t:'email',r:1}];
const NOTES_F={n:'notes',l:'Additional Notes',t:'textarea'};
const CONSENT_F={n:'consent',l:'I agree to be contacted about my enquiry.',t:'consent',r:1};
const EXTRAS={
'owner-management':[{n:'service',l:'Service Required',t:'select',r:1,o:['Property Management','Leasing','Vacation Home','Staff Accommodation','Not Sure']},{n:'ptype',l:'Property Type',t:'select',r:1,o:['Full building','Villa','Apartment','Labour & staff accommodation','Other']},{n:'emirate',l:'Emirate',t:'select',r:1,o:['Dubai','Sharjah','Ajman','Other']},{n:'area',l:'Area / Location',t:'text',r:1},{n:'units',l:'Number of Units / Rooms',t:'text'},{n:'status',l:'Current Status',t:'select',o:['Occupied','Partially occupied','Vacant']},{n:'rent',l:'Expected Rent / Property Value (optional)',t:'text'}],
'property-search':[{n:'intent',l:'Intent',t:'select',r:1,o:['Rent']},{n:'ptype',l:'Property Type',t:'select',r:1,o:['Apartment','Villa','Full building','Staff accommodation','Commercial','Other']},{n:'emirate',l:'Preferred Emirate',t:'select',r:1,o:['Dubai','Sharjah','Ajman','Other']},{n:'area',l:'Preferred Area',t:'text',r:1},{n:'budget',l:'Budget',t:'text'},{n:'timing',l:'Required Timing',t:'select',o:['Immediately','Within 1-3 months','Within 3-6 months','Just researching']}],
'staff-accommodation':[{n:'company',l:'Company Name',t:'text',r:1},{n:'count',l:'Number of Staff',t:'number',r:1},{n:'emirate',l:'Preferred Emirate',t:'select',r:1,o:['Dubai','Sharjah','Ajman','Other']},{n:'area',l:'Preferred Area',t:'text',r:1},{n:'date',l:'Required From',t:'date'},{n:'duration',l:'Expected Duration',t:'text'},{n:'budget',l:'Approximate Budget',t:'text'}],
'vacation-home':[{n:'location',l:'Property Location',t:'text',r:1},{n:'community',l:'Building / Community',t:'text'},{n:'bedrooms',l:'Number of Bedrooms',t:'select',o:['Studio','1','2','3','4','5+']},{n:'furnished',l:'Furnished Status',t:'select',o:['Furnished','Unfurnished']},{n:'occupancy',l:'Current Property Status',t:'text'},{n:'arrangement',l:'Preferred Arrangement',t:'select',o:['Revenue Management','Fixed Rental Arrangement','Not Sure']}]};
function Contact(){return <><Seo title="Contact Rokn Al Ahlam" description="Contact Rokn Al Ahlam for property management, leasing, staff accommodation and vacation homes across Dubai, Sharjah and Ajman."/><PageHero label="Contact" title="Tell Us What You Need. We’ll Take It From There." text="Whether you own a property, need management support, require staff accommodation, or are considering a vacation-home arrangement, start with a few details." image={HOME_HERO}/><section className="forms"><span className="anchor" id="list"/><span className="anchor" id="looking"/><span className="anchor" id="staff"/><span className="anchor" id="vacation"/><aside className="contact-info"><h2>Contact Details</h2><p className="ci-intro">Send the enquiry form, or contact the team directly. We will contact you regarding the next step.</p><div className="ci-item"><Mail size={18}/><div><span>Email</span><a href="mailto:info@roknalahlam.com">info@roknalahlam.com</a></div></div><div className="ci-item"><Phone size={18}/><div><span>Phone</span><a href="tel:+971556829779">+971 55 682 9779</a></div></div><div className="ci-item"><MapPin size={18}/><div><span>Areas served</span><p>Dubai, Sharjah and Ajman</p></div></div><h3 className="ci-sub">Before you start</h3><p className="ci-note">Choose the enquiry type that fits best. The form then shows the details relevant to that requirement.</p></aside><LeadForm id="enquiry"/></section></>}
function Footer(){return <footer><Logo/><p>Property management, leasing and vacation homes across Dubai, Sharjah and Ajman.</p><div><a href="mailto:info@roknalahlam.com"><Mail size={15}/> info@roknalahlam.com</a><a href="tel:+971556829779"><Phone size={15}/> +971 55 682 9779</a></div></footer>}
function ScrollToHash(){const l=useLocation();React.useEffect(()=>{if(l.hash){const e=document.getElementById(l.hash.slice(1));if(e)e.scrollIntoView()}},[l]);return null}
function App(){return <BrowserRouter><a className="skip-link" href="#main">Skip to content</a><ScrollToHash/><Header/><main id="main"><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/owners" element={<OwnerPage/>}/><Route path="/management" element={<Management/>}/><Route path="/vacation-homes" element={<Vacation/>}/><Route path="/brokerage" element={<Brokerage/>}/><Route path="/contact" element={<Contact/>}/></Routes></main><Footer/></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
